addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"              % "0.1.14")
addSbtPlugin("io.github.davidmweber"     % "flyway-sbt"                % "6.5.0")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"              % "2.4.2")
addSbtPlugin("ch.epfl.scala"             % "sbt-scalafix"              % "0.9.24")
addSbtPlugin("com.typesafe.sbt"          % "sbt-native-packager"       % "1.7.6")
addSbtPlugin("com.github.cb372"          % "sbt-explicit-dependencies" % "0.2.15")
